### ISSUE TITLE
Content Cleanup Tracking Issue

### ISSUE THREAD

**Issue by sguthals** [microsoft/Reactors#177]
This issue will serve as a list of things to do as we clean up content. The process for content cleanup has not yet started, so this will currently serve as a dumping ground for things that need to be done eventually. When content cleanup begins, we will prioritize this list and create a timeline of completion. 

## Random list of things to remember
- [ ] Update `VSCode` or `VS Code` to `Visual Studio Code`
- [ ] Get CELA approval for all datasets that are being used and ensure all disclaimers are present in the appropriate locations
- [ ] Get CELA approval for any external links that we include (blog posts, tutorials, etc) and ensure all disclaimers are present in the appropriate locations
- [ ] Make sure we have a downloaded version of each dataset also available to hold us over if the data set changes but we are reliant on it for an event
- [ ] Ensure proper setup instructions exist in ONE location and each module points to it
  - This includes all package installs and imports, setting up conda environments or otherwise, mac and pc, and maybe linux?
- [ ] Ensure all call back links appropriately call back to the correct modules (preferably on Learn, as in, anything that is a "reference" should probably be on Learn not be embedded in other workshop content.)
- [ ] All code should be commented and the comments should be above the code 
- [ ] All code should be introduced with English and summarized with English
- [ ] All questions should be answered in at least the Instructor notebook
- [ ] Refer to all "instructor" versions as truth and move backwards from there
- [ ] Make sure all capitalization is the same (machine learning)
- [ ] Make sure all words are spelled out and don't use abbreviations
- [ ] (from Kimberly) Verify titles in each module (.md file) are accurate, then update all references/link backs to them so the titles are consistently referenced.
         - [ ] Case in point, workshop-resources/ai-services/AI_1/README.md references 3 modules: Overview of Artificial Intelligence (which links to an Overview.md titled "Azure Cognitive Services Reactor Workshop", Computer Vision and Translator Text APIs" which links to a readme with same title, and "Face Identification with Face API" which leads to a readme called "Section 3: Face API".

From Kimberly regarding slides:
- [ ] In DS2_Full_Day, slide 32: The speaker notes don’t map to the slide in a way that makes sense. Worth a look.
- [ ] DS2 full and 3-hour decks looked virtually the same.
- [ ] Section numbers: In some slide decks, each section was denoted with a number in addition to the section title (ie section 2, section 1.1). However, the number wasn’t referenced again throughout that section or from other sections or the TOC. Because I didn’t see a purpose for them, I removed them.
- [ ] ML2, slide 27: I think a section title slide for “Naïve Bayes” was copied from the “k-means Clustering” title slide but the name was not updated. I renamed it appropriately.
- [ ] ML2 missing section?: The Agenda references a section called “Linear Regression (part 1)” but that section doesn’t exist in the file. I left the reference for now, as I assume there should be a part 1 (since we DO have part 2) 😊, but the content for Part 1 should be investigated and added.
- [ ] Web Dev 2, slide 20: the tutorial link in the speaker’s notes doesn’t work. I could not locate the page myself through searches.
- [ ] Web Dev 2, slide 85: This section is about face recognition and the Face API. Given current events, I think it should be heavily reviewed and possibly removed. I also mentioned this in the team meeting last week.
- [ ] Artificial Intelligence: The agenda slide content doesn’t entirely match the slide order or sections. I ended up moving the “Additional steps” to the end, and added a section title slide for “overview of AI”. Note that there are 2 parts for Computer Vision and Face Identification in the Agenda, but only one actual section for each in the deck contents (and they aren’t denoted as “part 1” “part 2”.
- [ ] Lastly, I made a couple tweaks to the Web Dev 2 and Artificial Intelligence decks after I made the pull request. I don’t think that changed the URL for either but wanted to call that out if so.

## Random list of advice for when we're writing future content
- [ ] Only do "Instructor" versions and then dial back for students if needed.
- [ ] Create a style guide (e.g. `machine learning`, not `Machine Learning` or `ML` unless a part of a name of a service).

**Comment by sguthals** [comment]
@KimberlyBolton1

I'm going to start tracking all of the random thoughts on content improvement here. 

Goals:
1. Create consistent experiences for customers
2. Make sure everything has been run by CELA for things like references to non-Microsoft content
3. Create a guide to Reactor content creation

This will be a complex process, so rather than starting with the process, I figured we could start with the tasks and then design a process 😄

**Comment by KimberlyBolton1** [comment]
@sguthals 
Love it.

**Comment by sguthals** [comment]
## TODO
These are things I don't want to forget to clean up:
- We need to update aka links to point to the new directories. In general, all of them will be outdated because we've updated the main branch to be called `main`:
  - aka.ms/Reactors_Online 
  - aka.ms/ReactorsDS_Python (Currently doesn't point to anything)
- We need to update links on the YouTube descriptions:
  - https://www.youtube.com/watch?v=VOUh1kgNY-4
  - https://www.youtube.com/watch?v=BNE-x3h642g
  - https://www.youtube.com/watch?v=20xp7KRPGXE
- Did not finish double checking these.

**Comment by mebaumb** [comment]
Checked all the Reactor Youtube accounts.
Also need to update: 
- https://www.youtube.com/watch?v=AB71rH3A4xc 
- https://www.youtube.com/watch?v=vlZjmjOj7_w 
- https://www.youtube.com/watch?v=clJN0MiTbwM

**Comment by meaghanlewis** [comment]
I just updated: 
- aka.ms/Reactors_Online
- aka.ms/asyncJS
- aka.ms/ReactorLiveAzureML
- aka.ms/ReactorLiveCleanData

**Comment by KimberlyBolton1** [comment]
@sguthals in line 212 of /online-event-resources/data-science-and-machine-learning/data-science-basics/Cleaning_and_Manipulating_Data.ipynb, did we mean to write `Seires` ? Feels like it should be 'Series'.

**Comment by sguthals** [comment]
@KimberlyBolton1 - You're right, it should be Series

**Comment by mebaumb** [comment]
I went through and check microsoft/reactorplanning and didn't see any incorrect links!

**Comment by KimberlyBolton1** [comment]
Added a todo to the list regarding titling.

**Comment by sguthals** [comment]
![Uploading team-picture.gif…]()
